// / — the findings brief (ui.md §1/§3): ranked actionable cards fronting the
// two rooms, generated by ETL threshold rules (ref/findings) — never model
// prose. Audience tags render as the README personas (OPERATIONS / PRODUCT).
// Ghost cards make what we deliberately did NOT build visible.

import { parseIntArray, parseTargetParams } from "@trace-insights/contracts";
import { Link } from "react-router";
import { z } from "zod";
import { ErrorState, GhostCard, ProvenanceChip, Skeleton } from "../components/shared/honesty.tsx";
import { Sparkline } from "../components/shared/microviz.tsx";
import { useData, useFilters, useRows } from "../data/DataContext.tsx";
import { count } from "../fmt.ts";
import { DEFAULT_FILTERS, type FilterState, filtersToSearch } from "../state/urlState.ts";
import { PageTitle } from "./PageScaffold.tsx";

const FindingRowQ = z.object({
  finding_id: z.string(),
  rank: z.number(),
  audience: z.string(),
  title: z.string(),
  metric_value: z.number().nullable(),
  metric_label: z.string().nullable(),
  sparkline: z.string(),
  series_start_day: z.string().nullable(),
  target_params: z.string(),
  provenance: z.string(),
  requires_enrichment: z.boolean(),
});
type Finding = z.infer<typeof FindingRowQ>;

/** target_params (rule-emitted) → route + pre-set filters. */
function targetLink(f: Finding, base: FilterState): string {
  const p = parseTargetParams(f.target_params);
  const filters: FilterState = { ...DEFAULT_FILTERS, includeDemo: base.includeDemo };
  if (typeof p.from === "string" && typeof p.to === "string")
    filters.window = { fromDay: p.from, toDay: p.to };
  if (typeof p.signature === "string" && p.signature) filters.signature = p.signature;
  if (typeof p.gap === "string" && p.gap) filters.gap = p.gap;
  const path =
    p.side === "ops" ? "/ops" : p.page === "usage" ? "/product/usage" : "/product/outcomes";
  return `${path}${filtersToSearch(filters)}`;
}

function AudienceTag({ audience }: { audience: string }) {
  const isOps = audience === "ops";
  return (
    <span
      className="rounded-sm px-1.5 py-0.5 text-[10px] font-semibold tracking-wider"
      style={{
        color: isOps ? "var(--color-ops)" : "var(--color-product)",
        background: isOps ? "var(--color-ops-soft)" : "var(--color-product-soft)",
      }}
    >
      {isOps ? "OPERATIONS" : "PRODUCT"}
    </span>
  );
}

function chipKind(p: string): "heuristic" | "curated" | "model" | null {
  return p === "heuristic" || p === "curated" || p === "model" ? p : null;
}

export function FindingsPage() {
  const { degraded } = useData();
  const filters = useFilters();
  const findings = useRows(FindingRowQ, "SELECT * FROM findings ORDER BY rank LIMIT 8", null);
  return (
    <div className="max-w-3xl">
      <PageTitle side={null} title="Findings" question="What should I act on this week?" />
      {findings.error && <ErrorState message={findings.error} />}
      {findings.loading && <Skeleton lines={5} />}
      {findings.rows && findings.rows.length === 0 && (
        <div className="mb-4 rounded border border-hairline bg-paper p-4 text-sm text-ink-3">
          No findings met their thresholds for this run.
        </div>
      )}
      <div className="flex flex-col gap-3">
        {(findings.rows ?? []).map((f) => {
          const kind = chipKind(f.provenance);
          const spark = parseIntArray(f.sparkline);
          return (
            <div
              key={f.finding_id}
              className="flex items-center justify-between gap-4 rounded border border-hairline bg-surface p-3"
            >
              <div className="min-w-0">
                <div className="mb-1 flex items-center gap-2">
                  <AudienceTag audience={f.audience} />
                  {kind && (
                    <ProvenanceChip kind={kind} method="threshold rule over derived tables" />
                  )}
                </div>
                <p className="text-sm text-ink">{f.title}</p>
              </div>
              <div className="flex shrink-0 items-center gap-4">
                {spark.length > 0 ? (
                  <Sparkline values={spark} width={90} height={30} />
                ) : f.metric_value !== null ? (
                  <div className="text-right">
                    <div className="text-lg font-semibold tabular text-ink">
                      {count(f.metric_value)}
                    </div>
                    <div className="text-[10px] text-ink-3">{f.metric_label}</div>
                  </div>
                ) : null}
                <Link
                  to={targetLink(f, filters)}
                  className="rounded border border-hairline px-2 py-1 text-xs font-medium text-ink-2 hover:border-ink-3"
                >
                  open →
                </Link>
              </div>
            </div>
          );
        })}
      </div>
      {degraded.any && (
        <p className="mt-3 text-xs text-ink-3">
          Enrichment did not run for this publish — only rule-only findings are shown; cards that
          need model-classified fields will appear on an enriched run.
        </p>
      )}
      <div className="mt-6 grid grid-cols-1 gap-3 md:grid-cols-2">
        <GhostCard
          title="Cost analysis"
          reason="Token usage in this telemetry captures single generations only (15–20× undercount); any cost figure would be invented."
        />
        <GhostCard
          title="Tool latency"
          reason="Durations record telemetry write time, not execution time; a 'slowest tool' view would rank noise."
        />
      </div>
    </div>
  );
}
