-- Output: enrich.j4 rows — verdict / abstention / error, exactly one row
-- per selected record (docs/architecture/llm.md invariant). Keyed by
-- (record id, job, prompt_version); written transactionally per batch.
-- UNIMPLEMENTED
